hunav_loader:
  ros__parameters:
    map: warehouse
    publish_people: true
    agents:
      - worker1
      - worker2
      - worker3
      - worker4
    worker1:
      id: 1
      skin: 0
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 4 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0 # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -3.5764
        y: -8.4912
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: -3.3975
        y: -8.4912
        h: 1.250000
      g1:
        x: -3.5764
        y: -8.4912
        h: 1.250000
    worker2:
      id: 2
      skin: 4
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 2 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 2   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: -4.3845
        y: -3.1482
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 1.5100
        y: -2.5920
        h: 1.250000
      g1:
        x: 1.6094
        y: 6.9419
        h: 1.250000
      g2:
        x: 1.5100
        y: -2.5920
        h: 1.250000
      g3:
        x: -4.3845
        y: -3.1482
        h: 1.250000
    worker3:
      id: 3
      skin: 3
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 5 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 1   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 30.0  # seg
        once: true
        vel: 0.8
        dist: 1.5
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 1.7683
        y: -9.2063
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: 1.76834
        y: 1.9564
        h: 1.250000
      g1:
        x: 6.0004
        y: 1.9167
        h: 1.250000
      g2:
        x: 1.76834
        y: 1.9564
        h: 1.250000
      g3:
        x: 1.7683
        y: -9.2063
        h: 1.250000
    worker4:
      id: 4
      skin: 2
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      behavior: 
        type: 3 # REGULAR=1, IMPASSIVE=2, SURPRISED=3, SCARED=4, CURIOUS=5, THREATENING=6
        configuration: 0   # def: 0, custom:1, random_normal:2, random_uniform:3
        duration: 40.0  # seg
        once: true
        vel: 0.6
        dist: 0.0
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 20.0
      init_pose:
        x: 5.7222
        y: -2.0955
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
        - g3
      g0:
        x: -3.2187
        y: -2.1550
        h: 1.250000
      g1:
        x: -3.3777
        y: -7.4583
        h: 1.250000
      g2:
        x: -3.2187
        y: -2.1550
        h: 1.250000
      g3:
        x: 5.7222
        y: -2.0955
        H: 1.250000